### PR TITLE
Scsitimeout

### PR DESCRIPTION
**Pull request by adrenlinerush**
This gives the ability to adjust the scsi timeout value that is set by the vmware tools installer.

### CODE REVIEW

**Comment by acjohnson** [comment]
@razorsedge are you able to review this PR?

**Comment by razorsedge** [comment]
@adrenlinerush The tow commits of you PR (7cfa83cb7c53e14ac5a75f58e3c39a9e2162cf61 and 278d3ae97399d29bed6bc0e68ac5bcc095f73d51) look good.  However, you managed to pick up a lot of the merge branches that already exist in `master`.  Was your `scsitimeout` branch created from `master` or `develop`?

**Comment by adrenlinerush** [comment]
I was based off the master branch, I can re-base off the develop branch.

**Comment by adrenlinerush** [comment]
Re- based...

**Comment by acjohnson** [comment]
+1 @razorsedge please review

**Comment by acjohnson** [comment]
I just tested this and it appears we are missing some things... On RHEL 5 the udevadm binary is missing, so you must use udevcontrol instead:

```shell
# EL5
# /sbin/udevcontrol reload_rules
```

However on RHEL 5, 6 and 7 simply re-loading the udev rules is not enough to set the SCSI timeout dynamically, you must run `start_udev` as well to make the new rules go into effect:

```shell
# EL 5,6, and 7 - Make udev rules go in to effect
# /sbin/start_udev
```

Example:

```shell
# sed -i 's/echo 180 /echo 14400 /g' /etc/udev/rules.d/99-vmware-scsi-udev.rules

# udevadm control --reload-rules

# cd /sys

# find . -name timeout
./devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:0/2:0:0:0/timeout
./devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:1/2:0:1:0/timeout

# cat './devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:0/2:0:0:0/timeout'
180

# cat './devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:1/2:0:1:0/timeout'
180

# /sbin/start_udev
Starting udev:                                             [  OK  ]

# cat './devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:0/2:0:0:0/timeout'
14400

# cat './devices/pci0000:00/0000:00:15.0/0000:03:00.0/host2/target2:0:1/2:0:1:0/timeout'
14400
```

**Comment by razorsedge** [comment]
@adrenlinerush Can you incorporate these findings into your PR?

**Comment by adrenlinerush** [comment]
Yeah, that's been added except I used the udev control trigger instead of udev_start for other than RHEL5.

**Comment by razorsedge** [comment]
Excellent.

One last, minor bit: can you update the README and the puppetdoc in the head of init.pp with the parameter details?

**Comment by adrenlinerush** [comment]
I think I got the doc updated.

**Comment by razorsedge** [comment]
@adrenlinerush Nice work.

**Comment by adrenlinerush** [comment]
@razorsedge when do you plan to make your next release?

**Comment by razorsedge** [comment]
[razorsedge/vmwaretools 5.1.0](https://forge.puppetlabs.com/razorsedge/vmwaretools/5.1.0/) has been released to the Forge.

**Pull request merged**
