### PR TITLE
Support strict_vars for Puppet 4

### PR DESCRIPTION
**Pull request by geoffdavis**
Make sure code passes spec tests when strict_vars is on.

This required removing support for passing parameters via global variables with an ENC, which has been deprecated since Puppet 3 .

### CODE REVIEW

**Comment by geoffdavis** [comment]
The only travis check that's failing is on Ruby version 1.8.7 due to the rspec version. I see there's a commit on master that pins rspec to < 11, I'll see if I can cherry-pick that commit.

**Comment by geoffdavis** [comment]
Another ruby Gem is squawking on 1.8.7 - gettext-setup-0.16. I'll see if I can pin that to an older version.

**Comment by geoffdavis** [comment]
I can't even get Ruby 1.8.7 to load on my Mac at this point with RVM. Suggest dropping support for 1.8.7 in travis.yml

**Comment by razorsedge** [comment]
@geoffdavis I recently solved the STRICT_VARS issue with my SNMP module without ripping out ENC support.  I also fixed all the gem issues in the `develop` branch.

**Pull request closed without merging**
